config/routes.rb
Rails.application.routes.draw do
  resources :question_types
  resources :categories
  resources :questions do
    collection do
      match 'search' => 'questions#search', via: [:get, :post], as: :search
    end
  end
  namespace :api, defaults: {format: :json} do
    resources :questions, :categories, :question_types
  end

  root 'questions#index'

end

app/controllers/api/question_types_controller.rb
class Api::QuestionTypesController < Api::BaseController
  private

    def question_type_params
      params.require(:question_type).permit(:qtype)
    end

    def query_params
      params.permit(:question_id, :qtype)
    end
end

app/controllers/question_types_controller.rb
class QuestionTypesController < ApplicationController
  before_action :set_question_type, only: [:show, :edit, :update, :destroy]

  # GET /question_types
  # GET /question_types.json
  #Function called when index view is rendered. Ransack is used for search
  def index
    q_param = params[:q]
    page = params[:page]

    @q = QuestionType.ransack q_param
    @question_types = @q.result.page(page)
  end

  # GET /question_types/1
  # GET /question_types/1.json
  def show
  end

  # GET /question_types/new
  def new
    @question_type = QuestionType.new
  end

  # GET /question_types/1/edit
  def edit
  end

  # POST /question_types
  # POST /question_types.json'
  # when create button is pushed in new question type
  def create
    @question_type = QuestionType.new(question_type_params)

    respond_to do |format|
      if @question_type.save
        format.html { redirect_to @question_type, notice: 'Question type was successfully created.' }
        format.json { render :show, status: :created, location: @question_type }
      else
        format.html { render :new }
        format.json { render json: @question_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_types/1
  # PATCH/PUT /question_types/1.json
  #When update  button is pushed in edit question type
  def update
    respond_to do |format|
      if @question_type.update(question_type_params)
        format.html { redirect_to @question_type, notice: 'Question type was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_type }
      else
        format.html { render :edit }
        format.json { render json: @question_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_types/1
  # DELETE /question_types/1.json
  # when destroy question type is called in index view
  def destroy
    @question_type.destroy
    respond_to do |format|
      format.html { redirect_to question_types_url, notice: 'Question type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

#Other functions 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_type
      @question_type = QuestionType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_type_params
      params.require(:question_type).permit(:question_type_name)
    end
end

app/helpers/api/question_types_helper.rb
module Api::QuestionTypesHelper
end

app/helpers/question_types_helper.rb
module QuestionTypesHelper
end

app/views/question_types/_form.html.erb
<%= form_for(@question_type) do |f| %>
  <% if @question_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_type.errors.count, "error") %> prohibited this question_type from being saved:</h2>

      <ul>
      <% @question_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="top-area">
</div>
<br>

<form class="form-inline">
    <div class="input-group">
      <%= f.text_field :question_type_name,
      class: 'form-control', placeholder: 'Frågetyp' %>
       <span class="input-group-btn" id="search.btn-addon"><button type="submit" class='btn btn-primary'>Lägg till</button></span>
    </div>
  </form>


<% end %>

app/views/question_types/edit.html.erb
<h1>Redigera frågetyp</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_type %> |
<%= link_to 'Back', question_types_path %>

app/views/question_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Frågetyper</h1>
<br>
<%= search_form_for @q do |f| %>
  <form class="form-inline">


<!--Search form-->
     <div class="input-group">
      <%= f.search_field :question_type_name_cont,
      class: 'form-control', placeholder: 'Sök...' %>
       <span class="input-group-btn" id="search.btn-addon"><button type="submit" class='btn btn-primary'>Sök Fågetyp</button></span>

    </div>
  </form>
<% end %>
<table class="table">
  <thead>
    <tr>
    <!--sort of column name in db table-->
      <th><%= sort_link(@q, :question_type_name, 'Frågetyp') %></th>
      <th>Redigera</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<!--show a list of question types in database-->
  <tbody>
    <% @question_types.each do |question_type| %>
      <tr>
        <td><%= question_type.question_type_name %></td>
        <td><%= link_to 'Visa', question_type %> |
        <%= link_to 'Redigera', edit_question_type_path(question_type) %> |
        <%= link_to 'Radera', question_type, method: :delete, data: { confirm: 'Tar du bort denna Frågetyp kommer alla frågor som har frågetypen bli frågetypslösa. Vill du ta bort?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= paginate @question_types %>
<br>
<%= link_to 'New Question type', new_question_type_path %>

app/views/question_types/new.html.erb
<h1>Lägg till ny frågetyp</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', question_types_path %>

app/views/question_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frågetyp</strong>
  <%= @question_type.question_type_name %>
</p>

<%= link_to 'Redigera', edit_question_type_path(@question_type) %> |
<%= link_to 'Tillbaka', question_types_path %>