config/routes.rb
Rails.application.routes.draw do
  resources :question_types
  resources :categories
  resources :questions do
    collection do
      match 'search' => 'questions#search', via: [:get, :post], as: :search
    end
  end
  namespace :api, defaults: {format: :json} do
    resources :questions, :categories, :question_types
  end

  root 'questions#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :questions, dependent: :nullify
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < Api::BaseController
  private

    def category_params
      params.require(:category).permit(:cat)
    end

    def query_params
      params.permit(:question_id, :cat)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    q_param = params[:q]
    page = params[:page]

    @q = Category.ransack q_param
    @categories = @q.result.page(page)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_name, :category_hex_code)
    end
end

app/helpers/api/categories_helper.rb
module Api::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="top-area">
</div>
<form class="form-inline">



<div class="col-md-6">
    <div class="form-group">
        <%= f.label "Kategori" %><br>
      <%= f.text_field :category_name, class: 'form-control' %>
       <span class="input-group-btn" id="search.btn-addon"></span>
    </div>
</div>

<div class="col-md-6">
 <fieldset class="form-group">
    <%= f.label "Hexkod" %><br>
    <%= f.text_field :category_hex_code, class: "form-control", placeholder: '#ABC123'  %>
  </fieldset>
</div>

<div class="col-md-12">
    <button type="submit" class='btn btn-primary'>Lägg till</button>
    </div>
    <br><br><br><br>

  </form>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<!--Redenr _form for categories-->
<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kategorier</h1>
<br>
<%= search_form_for @q do |f| %>
  <form class="form-inline">

<!--searchfield-->
     <div class="input-group">
      <%= f.search_field :category_name_cont,
      class: 'form-control', placeholder: 'Sök...' %>
       <span class="input-group-btn" id="search.btn-addon"><button type="submit" class='btn btn-primary'>Sök Kategori</button></span>
    </div>
  </form>
<% end %>
<table class="table">
  <thead>
    <tr>
    <!--sort links for table names-->
      <th><%= sort_link(@q, :category_name, 'Kategori') %></th>
      <th><%= sort_link(@q, :category_hex_code, 'Hexkod') %></th>
      <th>Redigera</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <!--show a list of categories in database-->
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category_name %></td>
        <td><%= category.category_hex_code%></td>
        <td><%= link_to 'Visa', category %> |
        <%= link_to 'Redigera', edit_category_path(category) %> |
        <%= link_to 'Radera', category, method: :delete, data: { confirm: 'Tar du bort denna kategori kommer alla frågor som tillhör kategorin bli kategorilösa. Vill du ta bort?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!--paginate makes several pages instead of a long list of categories-->
<%= paginate @categories %>

app/views/categories/new.html.erb
<h1>Lägg till ny kategori</h1>

<!--Redenr _form for categories-->
<%= render 'form' %>

<br>
<br>
<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kategori:</strong>
  <%= @category.category_name %>
</p>
<p>
<strong>Hexkod:</strong>
	  <%= @category.category_hex_code %>
</p>

<%= link_to 'Redigera', edit_category_path(@category) %> |
<%= link_to 'Tillbaka', categories_path %>